# Generated by Django 4.0.3 on 2022-03-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default='../static/images/profile_img.png', upload_to='profile_images/'),
        ),
    ]
